# change the followings to match your Github username and repo name
baseurl: "/juanllave.github.io" # the name of your github repo
url: "" # the url of your github pages

# site information used in page title, meta data etc.
title: "Juan Lozano Vallejo"
description: Project Manager | Communications Strategist

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Juan Lozano Vallejo
author-bio: I am Project Manager, fluent in both client and programmer/data scientist, and designer. I am also fluent in English and Spanish, I am learning French. I am a Communications Strategist and Political Consultant. I design and build briefs, presentations, and a variety of reports. I create and orchestrate communication campaigns from end-to-end based on sound research, data and facts.
author-image: IR-1515.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: What I Do
  permalink: wid
- text: Skills
  permalink: skills
- text: Values
  permalink: values
- text: Beyond Work
  permalink: beyond
- text: Resume
  permalink: resume
- text: Contact
  permalink: contact

# use false to turn off any social media links
facebook: false
instagram: false
linkedin: https://www.linkedin.com/in/juanlozanovallejo/
github: https://github.com/juanllave
twitter: https://twitter.com/JuanLlave
medium: false
google-scholar: false
email: mailto:juan.lozanovallejo@gmail.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
