# change the followings to match your Github username and repo name
baseurl: "/juanllave.github.io" # the name of your github repo
url: "" # the url of your github pages

# site information used in page title, meta data etc.
title: "Juan Lozano Vallejo"
description: Project Manager | Communications Strategist

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Juan Lozano Vallejo
author-bio: Project Manager | Communications Strategist
author-image: IR-1515.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Contact
  permalink: contact
- text: Skills
  permalink: skills
- text: Resume
  permalink: resume

# use false to turn off any social media links
facebook: false
instagram: false
linkedin: https://www.linkedin.com/in/juanlozanovallejo/
github: https://github.com/juanllave
twitter: https://twitter.com/JuanLlave
medium: false
google-scholar: false
email: mailto:juan.lozanovallejo@gmail.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
